### ISSUE TITLE
Group Kanban: Rails capstone @milen-ale & @acedavon

### ISSUE THREAD

**Issue by aceDavon** [aceDavon/Recipe-app#11]
## In this issue, the following are true for our project setup:

- [ ] We are a group of 2 person @milen-ale and @aceDavon
- [ ] We have properly setup the Kanban as required by the project 

_Here is a link to our Kanban: [Kanban Board](https://github.com/users/aceDavon/projects/4/views/1)_

**Comment by Reem-lab** [comment]
# Hi Team, 👋🏻👋🏻 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good working on set up the kanan 🔥🔥
- Great on assigning the tasks between the team 🔥🔥

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by aceDavon** [comment]
Thanks for your review, we are closing the issue now
